import { Communication } from "@openomni/protocol";
import { Storage } from "../storage/storage";
import { requireSubAdapter } from "../storage/timestamped-store";

/**
 * #510 D2a — PendingAskStore is FROZEN after its final accepted append
 * (#215 already retired every production write path; production writers were
 * zero at freeze time). Every write method throws the typed
 * `Communication.PendingAsk.FrozenError` (`data.code === "pending_ask_frozen"`)
 * and persists nothing; reads keep serving the immutable historical rows —
 * including the #519 upcast-on-read Wait view over `findByCorrelation`.
 * The archive manifest for the frozen `pending_ask` table is generated by
 * `script/generate-ledger-archive-manifest.ts` and verified by
 * `script/conformance/p2-ledger-baseline.test.ts`.
 */

function requireAdapter() {
  return requireSubAdapter(
    Storage.get().pendingAsk,
    "Storage adapter does not implement pendingAsk",
  );
}

// The retired write-method vocabulary lives only inside the FrozenError data
// (#498 C4 export diet) — derive it from there instead of a second export.
type FrozenWriteMethod = Communication.PendingAsk.FrozenError["data"]["method"];

function frozenWrite(method: FrozenWriteMethod): never {
  throw new Communication.PendingAsk.FrozenError({
    message: `PendingAskStore is frozen (#510 D2a): ${method} is retired — historical pending_ask rows are read-only archive`,
    code: "pending_ask_frozen",
    method,
  });
}

export namespace PendingAskStore {
  // Frozen writer: the Create input vocabulary is retired with the write
  // path (#498 C4), so the refused input is deliberately untyped.
  export function create(_input: unknown): never {
    frozenWrite("create");
  }

  export function get(id: string): Communication.PendingAsk.Record | undefined {
    return requireAdapter().get(id);
  }

  export function list(
    status?: Communication.PendingAsk.Status[],
  ): Communication.PendingAsk.Record[] {
    return requireAdapter().list(status);
  }

  export function findByCorrelation(
    query: Communication.PendingAsk.CorrelationQuery,
  ): Communication.PendingAsk.Record[] {
    return requireAdapter().findByCorrelation(
      Communication.PendingAsk.CorrelationQuery.parse(query),
    );
  }

  export function answer(
    _id: string,
    _patch: Partial<Pick<Communication.PendingAsk.Record, "answeredAt">> = {},
  ): never {
    frozenWrite("answer");
  }

  export function markAmbiguous(_id: string): never {
    frozenWrite("markAmbiguous");
  }

  export function cancel(_id: string): never {
    frozenWrite("cancel");
  }

  export function expire(_id: string): never {
    frozenWrite("expire");
  }
}
