import { WorkerRun as WorkerRunProtocol, type WorkItem } from "@openomni/protocol";
import { WorkerRunStateStore } from "./state-store.js";

/**
 * #510 D2b — WorkerRun is FROZEN (pending-ask/pending-interaction
 * precedent). The run lifecycle lives on WorkItem attempt facts
 * (`work_item.attempt_allocated` / `work_item.attempt_finished` on the
 * `work:<hash>` owner stream — see work-item/attempt-run.ts), so every
 * write method throws the typed `WorkerRun.FrozenError`
 * (`data.code === "worker_run_frozen"`) and persists nothing; reads keep
 * serving the immutable historical `worker_run_state` rows — including the
 * deterministic upcast-on-read attempt-run view in
 * `WorkItemAttemptRun.find`. The freeze also retired the store's Bus
 * publishers (`worker.run.*` production lifecycle events died with the
 * writes; the protocol schema stays on #497's kill list). The archive
 * manifest for the frozen table is generated by
 * `script/generate-ledger-archive-manifest.ts` and verified by
 * `script/conformance/p2-ledger-baseline.test.ts`.
 */

export type WorkerRunStatus = WorkerRunProtocol.Status;

export interface WorkerRunRecord {
  runId: string;
  sessionId: string;
  parentSessionId?: string;
  title: string;
  prompt: string;
  assignedStepId?: string;
  executorKind?: WorkItem.ExecutorKind;
  status: WorkerRunStatus;
  startedAt: number;
  endedAt?: number;
  lastMessageId?: string;
  error?: string;
  resumeCount: number;
  timeUpdated: number;
}

type WorkerRunStatusExtra = {
  endedAt?: number;
  lastMessageId?: string;
  error?: string;
};

const terminalStatuses: ReadonlySet<WorkerRunStatus> = new Set([
  "succeeded",
  "failed",
  "cancelled",
  "interrupted",
]);

function frozenWrite(method: WorkerRunProtocol.WriteMethod): never {
  throw new WorkerRunProtocol.FrozenError({
    message: `WorkerRun store is frozen (#510 D2b): ${method} is retired — run lifecycle lives on WorkItem attempt facts; historical worker_run_state rows are read-only archive`,
    code: "worker_run_frozen",
    method,
  });
}

function toWorkerRunRecord(record: WorkerRunStateStore.Record): WorkerRunRecord {
  return {
    runId: record.runId,
    sessionId: record.sessionId,
    parentSessionId: record.parentSessionId,
    title: record.title,
    prompt: record.prompt,
    assignedStepId: record.assignedStepId,
    executorKind: record.executorKind,
    status: record.status,
    startedAt: record.timeCreated,
    // Terminal legacy rows derive endedAt from their persisted update time;
    // the in-memory runExtras remainder is gone (attempt facts own endedAt/
    // lastMessageId for post-cutover runs).
    endedAt: terminalStatuses.has(record.status) ? record.timeUpdated : undefined,
    lastMessageId: undefined,
    error: record.error,
    resumeCount: record.resumeCount,
    timeUpdated: record.timeUpdated,
  };
}

export namespace WorkerRun {
  export async function create(
    _sessionId: string,
    _run: {
      runId: string;
      title: string;
      prompt: string;
      assignedStepId?: string;
      agentName?: string;
      parentSessionId?: string;
      executorKind?: WorkItem.ExecutorKind;
    },
  ): Promise<never> {
    frozenWrite("create");
  }

  export async function get(
    sessionId: string,
    runId: string,
  ): Promise<WorkerRunRecord | undefined> {
    const run = WorkerRunStateStore.get(sessionId, runId);
    return run ? toWorkerRunRecord(run) : undefined;
  }

  export async function listBySession(sessionId: string): Promise<WorkerRunRecord[]> {
    return WorkerRunStateStore.listBySession(sessionId).map(toWorkerRunRecord);
  }

  export async function listByStatus(status: WorkerRunStatus): Promise<WorkerRunRecord[]> {
    return WorkerRunStateStore.listByStatus(status).map(toWorkerRunRecord);
  }

  export async function updateStatus(
    _sessionId: string,
    _runId: string,
    _status: WorkerRunStatus,
    _extra?: WorkerRunStatusExtra,
  ): Promise<never> {
    frozenWrite("updateStatus");
  }

  export async function updateStatusIfCurrent(
    _sessionId: string,
    _runId: string,
    _expected: WorkerRunStateStore.StatusPrecondition,
    _status: WorkerRunStatus,
    _extra?: WorkerRunStatusExtra,
  ): Promise<never> {
    frozenWrite("updateStatusIfCurrent");
  }
}
