import { Communication } from "@openomni/protocol";
import { Storage } from "../storage/storage";
import { requireSubAdapter } from "../storage/timestamped-store";

/**
 * #548 — PendingInteractionStore is FROZEN (pending-ask precedent, #510 D2a).
 * Its dispatch-side consumers cut over to durable Wait correlation (#215), so
 * every write method throws the typed
 * `Communication.PendingInteraction.FrozenError`
 * (`data.code === "pending_interaction_frozen"`) and persists nothing; reads
 * keep serving the immutable historical rows — including the upcast-on-read
 * Wait view over `findByCorrelation`. Expiry is enforced at read time (the
 * follow-up-window filter below), never by mutation: the boot expiry sweep is
 * retired with a frozen-store no-op receipt in server recovery. The archive
 * manifest for the frozen `pending_interaction` table is generated by
 * `script/generate-ledger-archive-manifest.ts` and verified by
 * `script/conformance/p2-ledger-baseline.test.ts`.
 */

function requireAdapter() {
  return requireSubAdapter(
    Storage.get().pendingInteraction,
    "Storage adapter does not implement pendingInteraction",
  );
}

// The retired write-method vocabulary lives only inside the FrozenError data
// (#498 C4 export diet) — derive it from there instead of a second export.
type FrozenWriteMethod = Communication.PendingInteraction.FrozenError["data"]["method"];

function frozenWrite(method: FrozenWriteMethod): never {
  throw new Communication.PendingInteraction.FrozenError({
    message: `PendingInteractionStore is frozen (#548): ${method} is retired — historical pending_interaction rows are read-only archive`,
    code: "pending_interaction_frozen",
    method,
  });
}

function stillAcceptsFollowUp(
  record: Communication.PendingInteraction.Record,
  now: number,
): boolean {
  if (record.status === "open") return now <= record.expiresAt;
  if (
    (record.status !== "resolved" && record.status !== "follow_up") ||
    record.resolvedAt === undefined
  ) {
    return false;
  }
  return now <= record.resolvedAt + record.followUpWindow;
}

export namespace PendingInteractionStore {
  export type Record = Communication.PendingInteraction.Record;

  // Frozen writer: the Create input vocabulary is retired with the write
  // path (#498 C4), so the refused input is deliberately untyped.
  export function create(_input: unknown): never {
    frozenWrite("create");
  }

  export function get(id: string): Record | undefined {
    return requireAdapter().get(id);
  }

  export function findByCorrelation(
    query: Communication.PendingInteraction.CorrelationQuery,
    now = Date.now(),
  ): Record[] {
    return requireAdapter()
      .findByCorrelation(Communication.PendingInteraction.CorrelationQuery.parse(query))
      .filter((record) => stillAcceptsFollowUp(record, now));
  }

  export function resolve(_id: string, _patch: Partial<Pick<Record, "resolvedAt">> = {}): never {
    frozenWrite("resolve");
  }

  export function markFollowUp(_id: string): never {
    frozenWrite("markFollowUp");
  }

  export function cancel(_id: string, _patch: Partial<Pick<Record, "cancelledAt">> = {}): never {
    frozenWrite("cancel");
  }

  export function cleanupExpired(_now = Date.now()): never {
    frozenWrite("cleanupExpired");
  }
}
