import { TOPOLOGY, type DependencyBand, type WorkspaceTopology } from "./topology";

const START_MARKER = "<!-- BEGIN GENERATED TOPOLOGY -->";
const END_MARKER = "<!-- END GENERATED TOPOLOGY -->";
const AGENTS_PATH = new URL("../AGENTS.md", import.meta.url);

function shortPackageName(packageName: string): string {
  return packageName.replace("@openomni/", "");
}

function renderDependencies(dependencies: DependencyBand): string {
  if (dependencies === "none") {
    return "none";
  }
  if (dependencies === "any-except-self") {
    return "any workspace except itself";
  }
  return dependencies.map(shortPackageName).join(", ");
}

function renderWorkspaceName(workspace: WorkspaceTopology): string {
  return workspace.dir.startsWith("apps/")
    ? workspace.dir
    : shortPackageName(workspace.packageName);
}

export function renderTopology(topology: readonly WorkspaceTopology[] = TOPOLOGY): string {
  const consumersByDependency = new Map<string, string[]>();
  for (const workspace of topology) {
    if (!Array.isArray(workspace.allowedDeps)) {
      continue;
    }
    for (const dependency of workspace.allowedDeps) {
      const consumers = consumersByDependency.get(dependency) ?? [];
      consumers.push(renderWorkspaceName(workspace));
      consumersByDependency.set(dependency, consumers);
    }
  }

  const graph = topology
    .flatMap((workspace) => {
      const consumers = consumersByDependency.get(workspace.packageName);
      return consumers === undefined
        ? []
        : [`${renderWorkspaceName(workspace)} <- ${consumers.join(", ")}`];
    })
    .join("\n");

  const rows = topology
    .map((workspace) => {
      const sourceConstraint =
        workspace.srcAllowedDeps === undefined
          ? ""
          : `; \`src/\` may depend on ${renderDependencies(workspace.srcAllowedDeps)}`;
      return `| \`${renderWorkspaceName(workspace)}\` | ${renderDependencies(workspace.allowedDeps)}${sourceConstraint} |`;
    })
    .join("\n");

  return `${START_MARKER}\n<!-- Generated by script/generate-agents-deps.ts from script/topology.ts. Do not edit. -->\n\nRead \`X <- Y\` as Y may depend on X.\n\n\`\`\`text\n${graph}\n\`\`\`\n\n| Workspace | May depend on |\n| --- | --- |\n${rows}\n${END_MARKER}`;
}

function replaceGeneratedSection(document: string, generated: string): string {
  const start = document.indexOf(START_MARKER);
  const end = document.indexOf(END_MARKER);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`AGENTS.md must contain one ${START_MARKER}/${END_MARKER} section`);
  }
  const afterEnd = end + END_MARKER.length;
  return `${document.slice(0, start)}${generated}${document.slice(afterEnd)}`;
}

async function main(): Promise<void> {
  const current = await Bun.file(AGENTS_PATH).text();
  const expected = replaceGeneratedSection(current, renderTopology());

  if (process.argv.includes("--check")) {
    if (current !== expected) {
      console.error(
        "AGENTS.md dependency topology is stale. Run: bun run script/generate-agents-deps.ts",
      );
      process.exitCode = 1;
    } else {
      console.log("AGENTS.md dependency topology is current");
    }
  } else {
    await Bun.write(AGENTS_PATH, expected);
    console.log("Updated AGENTS.md dependency topology");
  }
}

if (import.meta.main) {
  await main();
}
