export { DiscordAdapter } from "./discord/surface.js";
export { DiscordNormalizer } from "./discord/normalizer.js";
export { TelegramAdapter } from "./telegram/surface.js";
export { GitHubAdapter } from "./github/surface.js";
export { WebSocketHandler } from "./websocket.js";
export { createGatewayRouter } from "./router/index.js";
export { WaitService } from "./router/wait/index.js";
export type { ChannelDeliveryRoute, GatewayRouter } from "./router/index.js";
export type { ExistingAgentMessaging } from "./router/messaging/send.js";
export type { PublishPort } from "./types.js";
